### ISSUE TITLE
Compensation plan issue

### ISSUE THREAD

**Issue by Renzono** [OriginProtocol/ousd-compensation-calculation#2]
What is your username on Discord, Telegram, or Twitter?
Norbert RABOLIN#3167
If you believe that the calculation of your compensation is incorrect, tell us your Ethereum account address.
0x70F6B0DC3d3Ae50E16f333949b25fd2b3bC2f8E2
If you believe that the calculation of your compensation is incorrect, explain why and tell us what amount(s) you expect to receive.
1124

**Comment by micahalcorn** [comment]
The pre-hack balance for this account was 437.35 OUSD. The increase to 1,124 occurred as a result of the manipulative rebases that the attacker caused.

**Comment by Renzono** [comment]
I made verifications and you are right . Sorry for this wrong request .Thank youNorbert RABOLINenvoyé : 3 février 2021 à 20:09de : Micah Alcorn <notifications@github.com>à : OriginProtocol/ousd-compensation-calculation <ousd-compensation-calculation@noreply.github.com>cc : Renzono <norbert.rabolin@wanadoo.fr>, Author <author@noreply.github.com>objet : Re: [OriginProtocol/ousd-compensation-calculation] Compensation plan issue (#2) The pre-hack balance for this account was 437.35 OUSD. The increase to 1,124 occurred as a result of the manipulative rebases that the attacker called.—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by micahalcorn** [comment]
No problem, thanks for being an early adopter @Renzono!
